### ISSUE TITLE
Bug-11122024-1 - filter "is.partially.or.fully.included.in.list" does not seem to work anymore

### ISSUE THREAD

**Issue by nexusops** [PaloAltoNetworks/pan-os-php#793]
## Describe the bug

filter "is.partially.or.fully.included.in.list" does not seem to work anymore

## Expected behavior

filter should identify rules based on the matching IP addresses or subnets

## Current behavior

Error output is produced

```
* processing ruleset 'PANConf: / VirtualSystem:vsys1 / RuleStore:Security' that holds 13402 rules
PHP Fatal error:  Uncaught Error: Call to undefined method IPMap::substract() in /tools/pan-os-php/lib/helper-classes/IPMap.php:131
Stack trace:
#0 /tools/pan-os-php/lib/misc-classes/filters/filters-Rule.php(707): IPMap->includedInOtherMap()
#1 /tools/pan-os-php/lib/misc-classes/filters/filters-Rule.php(985): {closure}()
#2 /tools/pan-os-php/lib/misc-classes/RQueryContext.php(54): {closure}()
#3 /tools/pan-os-php/lib/misc-classes/RQuery.php(161): RQueryContext->execute()
#4 /tools/pan-os-php/lib/misc-classes/RQuery.php(331): RQuery->matchSingleObject()
#5 /tools/pan-os-php/lib/misc-classes/RQuery.php(314): RQuery->matchSingleObject()
#6 /tools/pan-os-php/utils/lib/RULEUTIL.php(383): RQuery->matchSingleObject()
#7 /tools/pan-os-php/utils/lib/RULEUTIL.php(37): RULEUTIL->time_to_process_objects()
#8 /tools/pan-os-php/utils/lib/UTIL.php(217): RULEUTIL->utilStart()
#9 /tools/pan-os-php/lib/misc-classes/PH.php(1060): UTIL->__construct()
#10 /tools/pan-os-php/utils/pan-os-php.php(118): PH::callPANOSPHP()
#11 Command line code(1): require_once('...')
#12 {main}
  thrown in /tools/pan-os-php/lib/helper-classes/IPMap.php on line 131
```

## Steps to reproduce

1. Run the following command
`pan-os-php type=rule in=[offline_config] location=any 'filter=( (src is.partially.or.fully.included.in.list 10.0.0.0/8) )'`

- Version used: 2.1.29 (running inside Docker)

![image](https://github.com/user-attachments/assets/41e715f0-5d12-48a7-9c29-b5af38e430a4)

**Comment by nexusops** [comment]
re-tested in development version 2.1.30. Bug confirmed as fixed.
